# Generated by Django 4.2.6 on 2023-10-18 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_orderitem_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_created=True, default='2023-01-01'),
            preserve_default=False,
        ),
    ]
