# Generated by Django 4.2.6 on 2023-10-18 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_category_parent_alter_productimage_product_and_more'),
        ('order', '0007_order_status_alter_orderitem_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='product_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='product.productoption'),
        ),
    ]
